export const TOP_REGIONS = [
    {
        slug: 'bordeaux',
        name: 'Bordeaux',
        country: 'France',
        countryCode: 'FR',
        coordinates: [-0.5792, 44.8378], // lon, lat
        description: 'World-renowned for Cabernet Sauvignon and Merlot blends.',
    },
    {
        slug: 'burgundy',
        name: 'Burgundy',
        country: 'France',
        countryCode: 'FR',
        coordinates: [4.8322, 47.0260],
        description: 'The benchmark for Pinot Noir and Chardonnay.',
    },
    {
        slug: 'tuscany',
        name: 'Tuscany',
        country: 'Italy',
        countryCode: 'IT',
        coordinates: [11.2558, 43.7696],
        description: 'Home of Chianti, Brunello, and Super Tuscans.',
    },
    {
        slug: 'piedmont',
        name: 'Piedmont',
        country: 'Italy',
        countryCode: 'IT',
        coordinates: [7.6869, 45.0703],
        description: 'Famous for Barolo and Barbaresco (Nebbiolo).',
    },
    {
        slug: 'napa-valley',
        name: 'Napa Valley',
        country: 'USA',
        countryCode: 'US',
        coordinates: [-122.2869, 38.2975],
        description: 'Premier region for Cabernet Sauvignon in the New World.',
    },
    {
        slug: 'rioja',
        name: 'Rioja',
        country: 'Spain',
        countryCode: 'ES',
        coordinates: [-2.4456, 42.4658],
        description: 'Spain’s most famous region, known for Tempranillo.',
    },
    {
        slug: 'mosel',
        name: 'Mosel',
        country: 'Germany',
        countryCode: 'DE',
        coordinates: [7.0, 49.9],
        description: 'Steep slopes producing world-class Riesling.',
    },
    {
        slug: 'barossa-valley',
        name: 'Barossa Valley',
        country: 'Australia',
        countryCode: 'AU',
        coordinates: [138.95, -34.53],
        description: 'Famous for powerful Shiraz.',
    },
    {
        slug: 'champagne',
        name: 'Champagne',
        country: 'France',
        countryCode: 'FR',
        coordinates: [4.0333, 49.2583],
        description: 'The global standard for sparkling wine.',
    },
    {
        slug: 'mendoza',
        name: 'Mendoza',
        country: 'Argentina',
        countryCode: 'AR',
        coordinates: [-68.8272, -32.8895],
        description: 'High-altitude Malbec specialist.',
    },
];

export const YEARS_TO_FETCH = Array.from({ length: 20 }, (_, i) => 2024 - i); // [2024, 2023, ..., 2005]
