import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import mongoose from 'mongoose';
import Winery from '../lib/models/Winery';
import Region from '../lib/models/Region';
import { OpenAI } from 'openai'; // User needs this package or I use fetch
// Checking environment
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

// Simple interface for the bot's findings
interface DiscoveredWinery {
    name: string;
    description: string;
    location: string;
    websiteUrl?: string;
    wines: { name: string; type: string }[];
}

async function run() {
    console.log("🍷 Winery Hunter Bot Initializing...");

    if (!process.env.MONGODB_URI) throw new Error("Missing MONGODB_URI");
    if (!OPENAI_API_KEY) throw new Error("Missing OPENAI_API_KEY");

    await mongoose.connect(process.env.MONGODB_URI);

    // 1. Select Region (Hardcoded for now or args)
    // Let's do "Casablanca Valley" as user mentioned it
    const targetSlug = process.argv[2] || 'casablanca-valley';
    const regionDoc = await Region.findOne({ slug: targetSlug });

    if (!regionDoc) {
        console.error(`Region ${targetSlug} not found.`);
        process.exit(1);
    }

    console.log(`🎯 Targeting Region: ${regionDoc.name} (${regionDoc.country})`);

    // 2. Get Existing Wineries to avoid dupes
    const existing = await Winery.find({ region: regionDoc._id }).select('name slug').lean();
    const existingNames = existing.map(w => w.name.toLowerCase());
    console.log(`Found ${existing.length} existing wineries.`);

    // 3. Ask AI for Candidates
    const openai = new OpenAI({ apiKey: OPENAI_API_KEY });

    const prompt = `
    You are an expert Wine Data Assistant.
    List 5 famous or highly regarded wineries in the region "${regionDoc.name}" (${regionDoc.country}).
    
    CRITICAL RULES:
    1. Do NOT include these wineries (already exist): ${existingNames.join(', ')}.
    2. For each winery, provide:
       - Name
       - A rich, marketing-friendly description (2 paragraphs)
       - Physical Address/Location (City/Area)
       - Website URL (if known, else null)
       - 3 Representative Wines (Name, Type e.g., "Red", "White")
    
    Return pure JSON format:
    [
      { 
        "name": "...", 
        "description": "...", 
        "location": "...", 
        "websiteUrl": "...", 
        "wines": [{ "name": "...", "type": "..." }] 
      }
    ]
    `;

    console.log("🤖 Asking AI for recommendations...");

    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-4o",
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" }
        });

        const content = completion.choices[0].message.content;
        if (!content) throw new Error("No content from AI");

        // Parse JSON (Wrap in try catch for resilient parsing)
        const result = JSON.parse(content);
        const candidates: DiscoveredWinery[] = result.wineries || result; // Handle { wineries: [...] } or [...]

        console.log(`✨ AI found ${candidates.length} candidates.`);

        for (const candidate of candidates) {
            // Double check existence by Slug
            const slug = candidate.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

            const exists = await Winery.findOne({ slug });
            if (exists) {
                console.log(`⚠️ Skipping ${candidate.name} (Slug collision)`);
                continue;
            }

            console.log(`📝 Drafting: ${candidate.name}...`);

            // Create Draft
            await Winery.create({
                name: candidate.name,
                slug: slug,
                description: candidate.description,
                country: regionDoc.country,
                region: regionDoc._id, // Link by ID
                location: candidate.location,
                websiteUrl: candidate.websiteUrl,
                status: 'draft', // Key Field
                tier: 'Basic',
                wines: candidate.wines.map(w => ({
                    name: w.name,
                    type: w.type,
                    description: 'Generated by AI'
                })),
                imageUrl: null // User must upload or we implement scraping later
            });
        }

        console.log("\n✅ Mission Complete. Check Admin Panel for Drafts.");

    } catch (e) {
        console.error("AI Error:", e);
    }

    process.exit(0);
}

run();
