import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import mongoose from 'mongoose';
import Winery from '../lib/models/Winery';
import Region from '../lib/models/Region';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Checking environment
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;

// Simple interface for the bot's findings
interface DiscoveredWinery {
    name: string;
    description: string;
    location: string;
    websiteUrl?: string;
    wines: { name: string; type: string }[];
}

async function run() {
    console.log("🍷 Winery Hunter Bot Initializing (Gemini Edition)...");

    if (!process.env.MONGODB_URI) throw new Error("Missing MONGODB_URI");
    if (!GEMINI_API_KEY) throw new Error("Missing GEMINI_API_KEY or GOOGLE_API_KEY");

    await mongoose.connect(process.env.MONGODB_URI);

    // 1. Select Region (Hardcoded for now or args)
    // Let's do "Casablanca Valley" as user mentioned it
    const targetSlug = process.argv[2] || 'casablanca-valley';
    const regionDoc = await Region.findOne({ slug: targetSlug });

    if (!regionDoc) {
        console.error(`Region ${targetSlug} not found.`);
        process.exit(1);
    }

    console.log(`🎯 Targeting Region: ${regionDoc.name} (${regionDoc.country})`);

    // 2. Get Existing Wineries to avoid dupes
    const existing = await Winery.find({ region: regionDoc._id }).select('name slug').lean();
    const existingNames = existing.map(w => w.name.toLowerCase());
    console.log(`Found ${existing.length} existing wineries.`);

    // 3. Ask Gemini for Candidates
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({
        model: "gemini-1.5-flash",
        generationConfig: { responseMimeType: "application/json" }
    });

    const prompt = `
    You are an expert Wine Data Assistant.
    List 5 famous or highly regarded wineries in the region "${regionDoc.name}" (${regionDoc.country}).
    
    CRITICAL RULES:
    1. Do NOT include these wineries (already exist): ${existingNames.join(', ')}.
    2. For each winery, provide:
       - Name
       - A rich, marketing-friendly description (2 paragraphs)
       - Physical Address/Location (City/Area)
       - Website URL (if known, else null)
       - 3 Representative Wines. For each wine include:
         - Name
         - Type (Red, White)
         - Recent Vintages (List of numbers, e.g. [2019, 2020, 2021, 2022])
    
    Return pure JSON format with this structure:
    {
      "wineries": [
        { 
          "name": "...", 
          "description": "...", 
          "location": "...", 
          "websiteUrl": "...", 
          "wines": [{ "name": "...", "type": "...", "vintages": [2020, 2021] }] 
        }
      ]
    }
    `;

    console.log("🤖 Asking Gemini for recommendations...");

    try {
        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();

        console.log("Gemini Response received.");

        // Parse JSON
        const parsed = JSON.parse(text);
        const candidates: DiscoveredWinery[] = parsed.wineries || parsed;

        console.log(`✨ AI found ${candidates.length} candidates.`);

        for (const candidate of candidates) {
            // Double check existence by Slug
            const slug = candidate.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

            const exists = await Winery.findOne({ slug });
            if (exists) {
                console.log(`⚠️ Skipping ${candidate.name} (Slug collision)`);
                continue;
            }

            console.log(`📝 Drafting: ${candidate.name}...`);

            // Create Draft
            await Winery.create({
                name: candidate.name,
                slug: slug,
                description: candidate.description,
                country: regionDoc.country,
                region: regionDoc._id,
                location: candidate.location,
                websiteUrl: candidate.websiteUrl,
                status: 'draft',
                tier: 'Basic',
                wines: candidate.wines.map(w => ({
                    name: w.name,
                    type: w.type,
                    description: 'Generated by AI',
                    vintages: (w as any).vintages || [] // Save the vintages
                })),
                imageUrl: null
            });
        }

        console.log("\n✅ Mission Complete. Check Admin Panel for Drafts.");

    } catch (e: any) {
        console.error("AI Error:", e.message || e);
    }

    process.exit(0);
}

run();
